
<?php $messages = $element->getMessages(); ?>

<div class="control-group">
    <label class="control-label" for="<?= $element->getName();?>"><?= $element->getLabel();?></label>
    <div class="controls">
        <div class="input-append">
            <?= $this->formDateTime($element);?>
            <span class="add-on add_on_calendar"><i class="icon-calendar"></i></span>
        </div>
    </div>
</div>

<?php if (! empty($messages)): ?>
    <div>
        <p class="text-error"><strong>Errors:</strong><br />
            <?php foreach ($element->getMessages() as $message) : ?>
                <?= $message . '<br/>'; ?>
            <?php endforeach ?>
        </p>
    </div>
<?php endif ?>
